name: Deployment Image Update on EKS
on: 
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Install awscli
      run: sudo apt install awscli -y

    - name: configure AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Set up kubectl
      run: |
        VERSION=$(curl --silent https://storage.googleapis.com/kubernetes-release/release/stable.txt)
        curl https://storage.googleapis.com/kubernetes-release/release/$VERSION/bin/linux/amd64/kubectl -o kubectl
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    - name: Configure kubectl for EKS
      run: aws eks update-kubeconfig --name eks-cluster 

    - name: Update image in deployment
      run: kubectl set image deployment/ecomm-app app=nginx --record=true